--
-- VHDL Architecture IND.selection.masterVersion
--
-- Created:
--          by - silvan.zahno.UNKNOWN (WE6996)
--          at - 11:06:34 02.04.2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2018.1 (Build 12)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
LIBRARY gates;
  USE gates.gates.all;


ARCHITECTURE masterVersion OF selection IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL conditionA : std_uLogic;
   SIGNAL conditionB : std_uLogic;
   SIGNAL conditionC : std_uLogic;
   SIGNAL conditionD : std_uLogic;
   SIGNAL conditionE : std_uLogic;
   SIGNAL foreigner  : std_uLogic;
   SIGNAL lessThan25 : std_uLogic;
   SIGNAL married    : std_uLogic;
   SIGNAL woman      : std_uLogic;


   -- Component Declarations
   COMPONENT and2
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      in2  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT and3
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      in2  : IN     std_uLogic ;
      in3  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT inverter
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;
   COMPONENT or5
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      in2  : IN     std_uLogic ;
      in3  : IN     std_uLogic ;
      in4  : IN     std_uLogic ;
      in5  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : and2 USE ENTITY gates.and2;
   FOR ALL : and3 USE ENTITY gates.and3;
   FOR ALL : inverter USE ENTITY gates.inverter;
   FOR ALL : or5 USE ENTITY gates.or5;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I8 : and2
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => man,
         in2  => lessThan25,
         out1 => conditionD
      );
   I9 : and2
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => unmarried,
         in2  => moreThan25,
         out1 => conditionE
      );
   I5 : and3
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => unmarried,
         in2  => man,
         in3  => swiss,
         out1 => conditionA
      );
   I6 : and3
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => unmarried,
         in2  => swiss,
         in3  => lessThan25,
         out1 => conditionB
      );
   I7 : and3
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => woman,
         in2  => foreigner,
         in3  => unmarried,
         out1 => conditionC
      );
   I1 : inverter
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => unmarried,
         out1 => married
      );
   I2 : inverter
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => man,
         out1 => woman
      );
   I3 : inverter
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => swiss,
         out1 => foreigner
      );
   I4 : inverter
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => moreThan25,
         out1 => lessThan25
      );
   I10 : or5
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => conditionA,
         in2  => conditionB,
         in3  => conditionC,
         in4  => conditionD,
         in5  => conditionE,
         out1 => accept
      );

END masterVersion;
